### ISSUE TITLE
Optimize Google Firefox addon is abandoned

### ISSUE THREAD

**Issue by valentt** [bibanon/bibanon#11]
Optimize Google is abandoned - https://support.mozilla.org/en-US/questions/1009390

**Comment by pokeball99** [comment]
are u want this archive? if so u might want to head over to [archive team](archiveteam.org), although i dont know if they archive single programs/abandonware on request

**Comment by antonizoon** [comment]
Actually, we do archive and maintain source code of old or otherwise abandoned projects at the [BASLQC](http://github.com/BASLQC/BASLQC) (Software Liquidation Commission).

The code was already exported to Github here: https://github.com/phoglenix/OptimizeGoogle-defunct-

For this project in particular, since Google and Firefox has evolved so much recently, it would not really function outside the context of it's times, so I wouldn't do much beyond rescue some information and a design spec out of Sourceforge. A person who wants to continue the effort should probably rewrite it from scratch.

**Comment by pokeball99** [comment]
@antonizoon ah thanks for clearing that up,i wasn't sure if you did or not,thanks for clearing that up :D
