### ISSUE TITLE
Putting all content on IPFS

### ISSUE THREAD

**Issue by DonaldTsang** [bibanon/bibanon#14]
https://github.com/jamescarlyle/ipfs-wiki

**Comment by antonizoon** [comment]
Good to see, our forebears envisioned the concept of a git-based markdown decentralized wiki that could be shared and spread around using something GitTorrent if it were ever invented.

Since then however, we have moved over to MediaWiki to maintain our wiki especially its edit chain and special features like templates. But I'll keep this in mind especially for publishing content to IPFS.
